#!/usr/bin/env bash
dry_run="0"

if [ -z "$XDG_CONFIG_HOME" ]; then
    echo "no xdg config hom"
    echo "using ~/.config"
    XDG_CONFIG_HOME=$HOME/.config
fi

if [ -z "$DEV_ENV" ]; then
    echo "env var DEV_ENV needs to be present"
    exit 1
fi

if [[ $1 == "--dry" ]]; then
    dry_run="1"
fi

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

log "env: $DEV_ENV"

log "creating symlinks from: $1"
pushd $1 &> /dev/null
(
    # Include both files and directories in the find command
    configs=$(find . -mindepth 1 -maxdepth 1)

    for c in $configs; do
        # If it's .config or .local, process the contents inside them
        if [[ $(basename $c) == ".config" || $(basename $c) == ".local" ]]; then
            # Process the contents of .config or .local
            contents=$(find $c -mindepth 1 -maxdepth 1)
            for item in $contents; do
                if [ -d "$item" ]; then
                    target_dir="${XDG_CONFIG_HOME}/$(basename $item)"
                    log "    removing: rm -rf $target_dir"

                    if [[ $dry_run == "0" ]]; then
                        rm -rf $target_dir
                    fi

                    log "    creating symlink: ln -s $(realpath $item) $target_dir"
                    if [[ $dry_run == "0" ]]; then
                        ln -s $(realpath $item) $target_dir
                    fi
                elif [ -f "$item" ]; then
                    target_file="${XDG_CONFIG_HOME}/$(basename $item)"
                    log "    removing: rm -f $target_file"

                    if [[ $dry_run == "0" ]]; then
                        rm -f $target_file
                    fi

                    log "    creating symlink: ln -s $(realpath $item) $target_file"
                    if [[ $dry_run == "0" ]]; then
                        ln -s $(realpath $item) $target_file
                    fi
                fi
            done
        else
            # For regular files and directories, process normally
            if [ -d "$c" ]; then
                target_dir="${XDG_CONFIG_HOME}/$(basename $c)"
                log "    removing: rm -rf $target_dir"

                if [[ $dry_run == "0" ]]; then
                    rm -rf $target_dir
                fi

                log "    creating symlink: ln -s $(realpath $c) $target_dir"
                if [[ $dry_run == "0" ]]; then
                    ln -s $(realpath $c) $target_dir
                fi
            elif [ -f "$c" ]; then
                target_file="${XDG_CONFIG_HOME}/$(basename $c)"
                log "    removing: rm -f $target_file"

                if [[ $dry_run == "0" ]]; then
                    rm -f $target_file
                fi

                log "    creating symlink: ln -s $(realpath $c) $target_file"
                if [[ $dry_run == "0" ]]; then
                    ln -s $(realpath $c) $target_file
                fi
            fi
        fi
    done
)
popd &> /dev/null

