#!/usr/bin/env bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

grep=""
dry_run="0"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry)
            dry_run="1"
            ;;
        --*)
            grep="${1:2}"  
            ;;
        *)
            echo "Invalid argument: $1"
            exit 1
            ;;
    esac
    shift
done

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

log "RUN: grep: $grep, dry_run: $dry_run"

# Find scripts in subdirectories first
sub_dir_scripts=$(find "$script_dir/runs" -mindepth 2 -type f -executable | sort)

# Find scripts directly in the root of "runs"
root_scripts=$(find "$script_dir/runs" -mindepth 1 -maxdepth 1 -type f -executable | sort)

# Function to execute scripts
execute_scripts() {
    local scripts="$1"
    for s in $scripts; do
        if [[ -n "$grep" ]]; then
            if [[ "$s" == *"$grep"* ]]; then
                log "Running script: $s"
                if [[ $dry_run == "0" ]]; then
                    "$s"
                fi
            else
                log "grep \"$grep\" filtered out $s"
            fi
        else
            log "Running script: $s"
            if [[ $dry_run == "0" ]]; then
                "$s"
            fi
        fi
    done
}

# Execute subdirectory scripts first
execute_scripts "$sub_dir_scripts"

# Then execute root scripts
execute_scripts "$root_scripts"

