#!/usr/bin/env bash

set -e
RUNNING_GNOME=$([[ "$XDG_CURRENT_DESKTOP" == *"GNOME"* ]] && echo true || echo false)
if $RUNNING_GNOME; then
  gsettings set org.gnome.desktop.screensaver lock-enabled false
  gsettings set org.gnome.desktop.session idle-delay 0
fi

sudo apt-get update >/dev/null 2>&1
mkdir -p $HOME/personal

cd /tmp
GUM_VERSION="0.14.3" 
wget -qO gum.deb "https://github.com/charmbracelet/gum/releases/download/v${GUM_VERSION}/gum_${GUM_VERSION}_amd64.deb"
sudo apt-get install -y ./gum.deb
rm gum.deb
cd -

if ! command -v gum >/dev/null 2>&1; then
    echo "Error: gum installation failed. Exiting."
    exit 1
fi

sudo apt-get install -y curl >/dev/null 2>&1

answer1=$(gum choose "Yes" "No" --height 10 --header "Clone repository?")
if [[ "${answer1}" == "Yes" ]]; then
    echo "Cloning files..."
    sudo apt-get install -y git >/dev/null 2>&1
    email=$(gum input --placeholder "Enter your Git email")

name=$(gum input --placeholder "Enter your Git name")

git config --global user.email "$email"
git config --global user.name "$name"
    rm -rf "$HOME/dev"
    if git clone https://github.com/mertins3650/dev.git "$HOME/dev" >/dev/null; then
        echo "Clone successful!"
    else
        echo "Failed to clone repository. Exiting."
        exit 1
    fi
else
    echo "Exiting."
    exit 0
fi

answer2=$(gum choose "Yes" "No" --height 10 --header "Run initial setup?")
if [[ "${answer2}" == "Yes" ]]; then
    if [[ -d "$HOME/dev/run" && -x "$HOME/dev/run" ]]; then
        for script in "$HOME/dev/run/first"*; do
            source "$script"
        done
    else
        echo "Error: '$HOME/dev/run' is not a valid executable directory."
        exit 1
    fi
else
    echo "Exiting."
    exit 0
fi

if $RUNNING_GNOME; then
  gsettings set org.gnome.desktop.screensaver lock-enabled true
  gsettings set org.gnome.desktop.session idle-delay 300
fi

answer4=$(gum choose "Yes" "No" --height 10 --header "Reboot?\n\nRun setup2 after boot")
if [[ "${answer4}" == "Yes" ]]; then
    reboot
else
    echo "Exiting."
    exit 0
fi
