#!/usr/bin/env bash

#nodejs npm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  

nvm install 22

sudo NVM_DIR="$HOME/.nvm" /bin/bash -c "source $NVM_DIR/nvm.sh && npm install -g typescript-language-server typescript"
sudo NVM_DIR="$HOME/.nvm" /bin/bash -c "source $NVM_DIR/nvm.sh && npm install -g prettier"

#bun
curl -fsSL https://bun.sh/install | bash
