#!/usr/bin/env bash

# rust btw
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
rustup update
source $HOME/.cargo/env


sudo apt -y install python3


# lua btw
cargo install stylua
rm -rf /usr/local/go && tar -C /usr/local -xzf go1.23.4.linux-amd64.tar.gz

# luarocks
pushd /tmp/luarocks-3.11.0
(
    wget --output-document /tmp/luarocks.tar.gz https://luarocks.org/releases/luarocks-3.11.0.tar.gz
    tar zxpf /tmp/luarocks.tar.gz -C /tmp
    cd
    ./configure && make && sudo make install
)
popd

luarocks install luacheck

#nodejs npm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  

nvm install 22

sudo NVM_DIR="$HOME/.nvm" /bin/bash -c "source $NVM_DIR/nvm.sh && npm install -g typescript-language-server typescript"
sudo NVM_DIR="$HOME/.nvm" /bin/bash -c "source $NVM_DIR/nvm.sh && npm install -g prettier"

#bun
curl -fsSL https://bun.sh/install | bash
