#!/usr/bin/env bash

programs=(
    uwsm
    swayosd
    wofi
    mako
    hyprland
    hyprpaper
    hypridle
    hyprpolkitagent
    hyprland-qtutils
    hyprlock
    hyprshot
    waybar
    xdg-desktop-portal-hyprland
    xdg-desktop-portal-gtk
)

paru -Syu "${programs[@]}" --noconfirm --needed
