#!/usr/bin/env bash
paru -Syu opencode-bin yarn go nodejs npm pnpm postgresql postgresql-libs llvm clang cargo  --noconfirm --needed

install_go_binary() {
    local binary=$1
    local package=$2

    local gobin="${GOBIN:-$HOME/go/bin}"

    if command -v "$binary" >/dev/null 2>&1; then
        echo "$binary is already installed."
    else
        echo "Installing $binary..."
        go install "$package"
    fi
}

install_go_binary go-blueprint github.com/melkeydev/go-blueprint@latest
install_go_binary air github.com/air-verse/air@latest
install_go_binary sqlc github.com/sqlc-dev/sqlc/cmd/sqlc@latest
install_go_binary goose github.com/pressly/goose/v3/cmd/goose@latest
install_go_binary templ github.com/a-h/templ/cmd/templ@latest
