#!/usr/bin/env bash
paru -Syu --noconfirm --needed docker docker-compose

echo '{"log-driver":"json-file","log-opts":{"max-size":"10m","max-file":"5"}}' | sudo tee /etc/docker/daemon.json

sudo systemctl enable docker

sudo usermod -aG docker ${USER}
