#!/usr/bin/env bash

programs=(
    docker
    docker-compose
)

paru -Syu "${programs[@]}" --noconfirm --needed

echo '{"log-driver":"json-file","log-opts":{"max-size":"10m","max-file":"5"}}' | sudo tee /etc/docker/daemon.json

sudo systemctl enable docker

sudo usermod -aG docker ${USER}
