#!/usr/bin/env bash


rm -rf $HOME/personal/ghostty 
git clone https://github.com/ghostty-org/ghostty.git $HOME/personal/ghostty 

(
cd $HOME/personal/ghostty
zig build -p $HOME/.local -Doptimize=ReleaseFast
)
