#!/usr/bin/env bash

sudo apt update
sudo apt install llvm lld llvm-dev liblld-dev clang libclang-dev libglib2.0-dev libgtk-4-dev libadwaita-1-dev git

LATEST_VERSION=$(curl -s https://ziglang.org/download/index.json | jq -r 'keys[] | select(test("^[0-9]+\\.[0-9]+\\.[0-9]+$"))' | sort -V | tail -n 1)

URL="https://ziglang.org/download/${LATEST_VERSION}/zig-linux-x86_64-${LATEST_VERSION}.tar.xz"
INSTALL_DIR="$HOME/.local/zig"

wget "$URL" -O /tmp/zig.tar.xz
rm -rf "$INSTALL_DIR"
mkdir -p "$INSTALL_DIR"
tar -xvf /tmp/zig.tar.xz --strip-components=1 -C "$INSTALL_DIR"
export PATH="$INSTALL_DIR:$PATH"


#wget https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz -O /tmp/zig.tar.xz
#tar -xvf /tmp/zig.tar.xz -C $HOME/.local
#export PATH="$HOME/.local/zig-linux-x86_64-0.13.0:$PATH"

rm -rf $HOME/personal/ghostty
git clone https://github.com/ghostty-org/ghostty $HOME/personal/ghostty

(
cd $HOME/personal/ghostty
zig build -p $HOME/.local -Doptimize=ReleaseFast
)
