#!/usr/bin/env bash

# Install Go if not already installed
paru -Syu go --noconfirm --needed

# Function to install a Go binary if not already installed
install_go_binary() {
    local binary=$1
    local package=$2

    # Determine install path (default to ~/go/bin if GOBIN not set)
    local gobin="${GOBIN:-$HOME/go/bin}"

    if command -v "$binary" >/dev/null 2>&1; then
        echo "$binary is already installed."
    else
        echo "Installing $binary..."
        go install "$package"
    fi
}

install_go_binary air github.com/air-verse/air@latest
install_go_binary sqlc github.com/sqlc-dev/sqlc/cmd/sqlc@latest
install_go_binary goose github.com/pressly/goose/v3/cmd/goose@latest

