#!/usr/bin/env bash
paru -Syu kvantum-qt5 --noconfirm --needed

gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
