#!/usr/bin/env bash

programs=(
    linux-headers
    impala
    satty
    lsof
    feh
    pavucontrol
    brightnessctl
    nautilus
    wl-clipboard
)

paru -Syu "${programs[@]}" --noconfirm --needed
