#!/usr/bin/env bash

programs=(
    linux-headers
    prettierd
    networkmanager
    lsof
    feh
    pavucontrol
    brightnessctl
    nautilus
    wl-clipboard
)

paru -Syu "${programs[@]}" --noconfirm --needed
sudo systemctl enable NetworkManager
